modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="cloverite"
version="2.2.0"
displayName="Four Leaf Crystal "
displayURL="https://modrinth.com /mod/fourleafcrystal"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cloverite]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cloverite]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration